### PR TITLE
Update ExprTk to 0.0.3

### PR DESCRIPTION
**Pull request by ArashPartow**
Release notes: https://www.partow.net/programming/exprtk/exprtk_release_notes_v0.0.3.txt

### CODE REVIEW

**Review by RalphSteinhagen — APPROVED** [review]
I will merge the PR since the code is identical to the [main repo](https://github.com/ArashPartow/exprtk) head.

**Comment by RalphSteinhagen** [comment]
@ArashPartow, thank you very much for your proactive work in bumping the `exprTk` version in this PR to the latest one. I commend your excellent work regarding `exprTk`. It’s much appreciated! :+1: :pray: 

We are modernising the code base, and this repo's `main` branch will be functionally replaced by GNU Radio 4.0 (GR4) and its new compile-time functionality. We are evaluating the possibility of making `exprTk` a mainstream feature of the upcoming GNU Radio 4.0 release. The aim is to use `exprTk` in runtime/user-configurable processing blocks within high-performance signal processing contexts. Your `exprTk` library's lightweight nature and flexibility align well with the dynamic requirements of our GR4 use case.

Thus, I have a few questions:  
1. **Getting in Contact**: Is there another way to contact you other than via GitHub?  
2. **ExprTk Status**: Do you consider `exprTk` feature-complete and offered “as-is,” or are you open to accepting pull requests for enhancements? Specifically:  
   - making the library compatible with more modern compilers (e.g. addressing issues with Clang19).  
   - modernising the codebase to leverage features from newer C++ standards (C++20/23).
   - ... what are your goals on this?

Thanks in advance, and keep up the good work!

<sub>*As a side comment: I’ve used `exprTk` in benchmarks to illustrate compile-time versus runtime trade-offs, particularly highlighting inefficiencies in modern compilers. While compilers are becoming more powerful, they often impose significant compile-time overhead without proportional runtime performance improvements. This has become a critical factor in GNU Radio 4.0, where compilation of even simple compile units can take up to 14 minutes due to runtime polymorphism and the need for flexible, user-defined flow graphs. Maybe you have experience with this sort of thing.*</sub>

**Comment by ArashPartow** [comment]
@RalphSteinhagen Thanks for merging the PR. 

Here are some answers to your questions:

> 1. **Getting in Contact**: Is there another way to contact you other than via GitHub?

For any issues or questions feel to reach out directly: https://www.partow.net/contact.html


> 2\. are you open to accepting pull requests for enhancements?

Yes always open to improvements of the library.  I'm currently in the process of bringing it to be based on C++17. As it has a user-base that requires a wide range of C++ standards (all the way back to C++03), it's been a long process, but for now 17 will be the target going forward.  

That being said, I'd prefer prior to coding anything up that it be discussed first. As most often than not, the ideas are good, but the implementations people provide can leave a lot to be desired and I'd rather get ahead of people putting time/effort into coding something up only then to realise there's a _better_ alternative. 

wrt to compiler versions, at the moment ExprTk builds error and warning free up to and including  GCC 14 and Clang 20 and the latest msvc (as of about 3 weeks ago), If there's any new issues please reach out and let me know.

Generally when considering new features, the main or primary objective is to maintain API stability, which has been stable for the last 18 years, the next objective prioritising features that would be needed in the library specifically - eg: I get a lot of requests to add people's desired functions to the library, but that's why the custom user defined functions are there etc.
The short of it, I'm happy to investigate any new features people are after, but they have to be balanced with the requirement of keeping the library stable and generally performant for most if not all its current users.

>  This has become a critical factor in GNU Radio 4.0, where compilation of even simple compile units can take up to 14 minutes

This is a really painful part of C++ in general. However wrt ExprTk, what a lot of people don't realise is that a large portion  of time taken for builds is not due to compilation but rather linking, and that simply using a more modern linker other than **ld** can reduce overall build times significantly _(at least wrt ExprTk)_.  

A similar question was raised recently [here](https://github.com/LMMS/lmms/pull/7571#issuecomment-2486932328)

**Comment by RalphSteinhagen** [comment]
@ArashPartow thanks for your swift and detailed response!


> Yes always open to improvements of the library. I'm currently in the process of bringing it to be based on C++17. [..] I'd prefer prior to coding anything up that it be discussed first.

Excellent! Great that exprTk is moving towards C++17, and I completely agree with your approach. Aligning ideas before investing time and effort into implementations and PRs is important. I understand that you need/want to support a broad range of C++ standards. Since you are already actively working on the C++17 modernisation, there are no immediate PRs from my side at this moment.

> [..] ExprTk builds error and warning free up to and including GCC 14 and Clang 20 [..]

I encountered the following errors with Clang-19:
<details>

<summary>click here to expand</summary>

```bash
clang-19  -pedantic-errors -Wall -Wextra -Werror -Wno-long-long -O1 -o exprtk_benchmark exprtk_benchmark.cpp -L/usr/lib -lstdc++ -lm
In file included from exprtk_benchmark.cpp:26:
./exprtk.hpp:6348:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
6348 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
     |                                                 ^
./exprtk.hpp:6408:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
6408 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
     |                                                 ^
./exprtk.hpp:6471:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
6471 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
     |                                                 ^
./exprtk.hpp:6515:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
6515 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
     |                                                 ^
./exprtk.hpp:7959:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
7959 |             expression_node<T>::ndb_t::template collect(index_, node_delete_list);
     |                                                 ^
./exprtk.hpp:12205:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
12205 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
      |                                                 ^
./exprtk.hpp:15672:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
15672 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
      |                                                 ^
./exprtk.hpp:15723:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
15723 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
      |                                                 ^
./exprtk.hpp:15790:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
15790 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
      |                                                 ^
./exprtk.hpp:15857:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
15857 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
      |                                                 ^
./exprtk.hpp:16425:49: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
16425 |             expression_node<T>::ndb_t::template collect(branch_, node_delete_list);
      |                                                 ^
11 errors generated.
```

```bash
clang-19 --version
clang version 19.1.3
Target: x86_64-suse-linux
Thread model: posix
InstalledDir: /usr/bin
```
</details>

Possibly just a minor issue and fixed by you in your local (?) branch. We haven't transitioned to Clang-19 for our native builds yet, though Emscripten has upgraded to Clang-19 and Clang-20 (i.e. Clang's trunk version). Would you like to add GH CI workers to test against gcc, clang, etc.? We have some experience/reference for that.

> A large portion of time taken for builds is not due to compilation but rather linking...

We have already explored some low-hanging fruit optimisations, using Clang's `-ftime-trace` and related tooling. Unfortunately, the build traces indicate that the back-end optimiser consumes the majority of the time (~9" out of 14"): 
image
The other parts are due to the type-multiplicity and needing to support runtime type-polymorphism of ~150 converter blocks that handle various fundamental type conversions (e.g., from a `uint8_t` to `float` data stream)

Here are the ClangFormat ouput:
 * 206 seconds [w/o runtime polymorphism/plugins enabled](https://github.com/user-attachments/files/17846985/qa_Converter_wo_plugin.txt)
 * 824 seconds [w/ runtime polymorphism/plugins enabled](https://github.com/user-attachments/files/17846980/qa_Converter_w_plugin.txt)

Your insights, expertise, and suggestions on mitigating these meta-programming/compiler-optimisation-related overheads would be greatly appreciated. My impression was that some of the issues are similar to your library. 
Maybe we could learn and profit from each other's experiences.


> For any issues or questions feel to reach out directly: https://www.partow.net/contact.html

Thanks, and I will do ... maybe there are some areas we could further collaborate on.


Thanks again for your continued support (wow 18 years) and for maintaining such a valuable open-source library!

**Comment by ArashPartow** [comment]
@RalphSteinhagen : wrt 

> I encountered the following errors with Clang-19:

Are you sure you're  using ExprTk 0.0.3? 

----------------

I'll rerun my analysis, though your results do look to be covering the main issues. Just to confirm is this with O3 level of optimisations? 

Also is your clang/llvm build a release build? 

fyi I use the following to build clang from tip:  [clangbuild.sh](https://github.com/user-attachments/files/18014330/clangbuild.sh__.txt)

**Comment by RalphSteinhagen** [comment]
@ArashPartow thanks for getting back. 

I tried to reproduce this with a [basic example](https://compiler-explorer.com/z/Mjr6M6aT6) on compiler-explorer, but the compile times—even for the simplest example—are a bit too long, and the job is cancelled by the backend.

> Are you sure you're using ExprTk 0.0.3?

Yes, I believe. I am using the head of 'master' at https://github.com/ArashPartow/exprtk

I am using the pre-build clang-19 from OpenSuSE:
```bash
clang++-19 --version
clang version 19.1.4
Target: x86_64-suse-linux
Thread model: posix
InstalledDir: /usr/bin
```

I realised that the GH repo seems to be only a mirror and does not collect issues/PRs. If there is a better source, please let me know. 

Once the compiler-feature is sorted out, I'd start integrating this into GR4.

Thanks in advance and your help is much appreciated.

**Comment by ArashPartow** [comment]
In your copy of ExprTk, can you tell me which line you're seeing: _expression_node<T>::ndb_t::template collect(_

In 0.0.3 the line 6348 is something else:  https://github.com/ArashPartow/exprtk/blob/0.0.3/exprtk.hpp#L6348

**Comment by RalphSteinhagen** [comment]
@ArashPartow I am feeling a bit embarassed. :see_no_evil: 

I must have had a different exprtk revision and/or compiler. With the latest master and (apparently) newer clang++-19 the error above doesn't occur anymore. Didn't go into bisecting the branch/compiler version but since this works without errors (`-Werror`) I would use this as is.

Sorry for the troubles. _mea culpa maxima est_

**Pull request merged**
